// const declaration creates a read-only reference to a value

// here we load the express javascript library
const express = require('express');

// here we get an express app object generated by the express() function
const app = express();

// here we define a string as the target url
const targetBaseUrl = 'http://www.letsboot.com/';



// this function will be called on every request
function handleRedirect(req, res) {
  // combine the original url with our target website
  const targetUrl = targetBaseUrl + req.originalUrl;

  // tell the response object ob express to redirect
  // this sends a HTTP Response with the Code 301 and a line
  // Location: targetUrl
  res.redirect(targetUrl);
}

// this registers our handleRedirect function for all 
// HTTP GET requests
app.get('*', handleRedirect);

// here we define the port number for which our express webserver shoul listen too
// either it should be provided by the environment (important for cloud hosting)
// or it should use 3000 if not set (ie. on your machine)
const port = process.env.port || 3000;

// now we tell the express app to listen to that port which makes it start the webservser
app.listen(port);